### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../output/ORannotation_ORs_pro.fa'

### ISSUE THREAD

**Issue by tachengtatangi** [ToHanwei/Genome2OR#2]
**The third step does not work:**
**I use the command:**
python IdentifyFunc.py ../output/ORannotation_ORs_pro.fa ../output/ORannotation_ORs_dna.fa -o ../output -p Identity -v
**But there is a problem:**
2022-07-03 00:03:07,255 Functions.py:INFO ###IdentityFunc program starts running###
2022-07-03 00:03:07,256 Functions.py:INFO function platform_info() is running
The system you use is Linux.
Python3 is used.
2022-07-03 00:03:07,256 Functions.py:INFO platform_info use 0.000 seconds
Process hit sequence file...
2022-07-03 00:03:07,256 Functions.py:INFO function refact_hitfile() is running
Traceback (most recent call last):
  File "/home/HHJ/getOR/Genome2OR/scripts/IdentifyFunc.py", line 56, in <module>
    template, hit_dict = refact_hitfile(hitpro)
  File "/home/HHJ/getOR/Genome2OR/scripts/src/Functions.py", line 36, in logtimer
    temp = func(*args, **kwargs)
  File "/home/HHJ/getOR/Genome2OR/scripts/src/Functions.py", line 719, in refact_hitfile
    seqlist = ReadSampleFasta(hitfile)
  File "/home/HHJ/getOR/Genome2OR/scripts/src/Functions.py", line 662, in ReadSampleFasta
    with open(seqfile) as seqf:
FileNotFoundError: [Errno 2] No such file or directory: '../output/ORannotation_ORs_pro.fa'

**In addition, there are many spelling mistakes in your document. Correcting them will make people less detours.**

**Comment by johnnymundi** [comment]
Yeah, I have found the same error, unfortunately...

**Comment by ToHanwei** [comment]
> **The third step does not work:** **I use the command:** python IdentifyFunc.py ../output/ORannotation_ORs_pro.fa ../output/ORannotation_ORs_dna.fa -o ../output -p Identity -v **But there is a problem:** 2022-07-03 00:03:07,255 Functions.py:INFO ###IdentityFunc program starts running### 2022-07-03 00:03:07,256 Functions.py:INFO function platform_info() is running The system you use is Linux. Python3 is used. 2022-07-03 00:03:07,256 Functions.py:INFO platform_info use 0.000 seconds Process hit sequence file... 2022-07-03 00:03:07,256 Functions.py:INFO function refact_hitfile() is running Traceback (most recent call last): File "/home/HHJ/getOR/Genome2OR/scripts/IdentifyFunc.py", line 56, in template, hit_dict = refact_hitfile(hitpro) File "/home/HHJ/getOR/Genome2OR/scripts/src/Functions.py", line 36, in logtimer temp = func(*args, **kwargs) File "/home/HHJ/getOR/Genome2OR/scripts/src/Functions.py", line 719, in refact_hitfile seqlist = ReadSampleFasta(hitfile) File "/home/HHJ/getOR/Genome2OR/scripts/src/Functions.py", line 662, in ReadSampleFasta with open(seqfile) as seqf: FileNotFoundError: [Errno 2] No such file or directory: '../output/ORannotation_ORs_pro.fa'
> 
> **In addition, there are many spelling mistakes in your document. Correcting them will make people less detours.**

Thank you for your advice. As you perform Step three, make sure that steps one and two are correct. In particular, you need to check that the output file is correct at each step.

**Comment by ToHanwei** [comment]
> **The third step does not work:** **I use the command:** python IdentifyFunc.py ../output/ORannotation_ORs_pro.fa ../output/ORannotation_ORs_dna.fa -o ../output -p Identity -v **But there is a problem:** 2022-07-03 00:03:07,255 Functions.py:INFO ###IdentityFunc program starts running### 2022-07-03 00:03:07,256 Functions.py:INFO function platform_info() is running The system you use is Linux. Python3 is used. 2022-07-03 00:03:07,256 Functions.py:INFO platform_info use 0.000 seconds Process hit sequence file... 2022-07-03 00:03:07,256 Functions.py:INFO function refact_hitfile() is running Traceback (most recent call last): File "/home/HHJ/getOR/Genome2OR/scripts/IdentifyFunc.py", line 56, in template, hit_dict = refact_hitfile(hitpro) File "/home/HHJ/getOR/Genome2OR/scripts/src/Functions.py", line 36, in logtimer temp = func(*args, **kwargs) File "/home/HHJ/getOR/Genome2OR/scripts/src/Functions.py", line 719, in refact_hitfile seqlist = ReadSampleFasta(hitfile) File "/home/HHJ/getOR/Genome2OR/scripts/src/Functions.py", line 662, in ReadSampleFasta with open(seqfile) as seqf: FileNotFoundError: [Errno 2] No such file or directory: '../output/ORannotation_ORs_pro.fa'
> 
> **In addition, there are many spelling mistakes in your document. Correcting them will make people less detours.**

**Comment by ToHanwei** [comment]
> **The third step does not work:** **I use the command:** python IdentifyFunc.py ../output/ORannotation_ORs_pro.fa ../output/ORannotation_ORs_dna.fa -o ../output -p Identity -v **But there is a problem:** 2022-07-03 00:03:07,255 Functions.py:INFO ###IdentityFunc program starts running### 2022-07-03 00:03:07,256 Functions.py:INFO function platform_info() is running The system you use is Linux. Python3 is used. 2022-07-03 00:03:07,256 Functions.py:INFO platform_info use 0.000 seconds Process hit sequence file... 2022-07-03 00:03:07,256 Functions.py:INFO function refact_hitfile() is running Traceback (most recent call last): File "/home/HHJ/getOR/Genome2OR/scripts/IdentifyFunc.py", line 56, in template, hit_dict = refact_hitfile(hitpro) File "/home/HHJ/getOR/Genome2OR/scripts/src/Functions.py", line 36, in logtimer temp = func(*args, **kwargs) File "/home/HHJ/getOR/Genome2OR/scripts/src/Functions.py", line 719, in refact_hitfile seqlist = ReadSampleFasta(hitfile) File "/home/HHJ/getOR/Genome2OR/scripts/src/Functions.py", line 662, in ReadSampleFasta with open(seqfile) as seqf: FileNotFoundError: [Errno 2] No such file or directory: '../output/ORannotation_ORs_pro.fa'
> 
> **In addition, there are many spelling mistakes in your document. Correcting them will make people less detours.**

-o ORannotation
